# Docker Compose for All-At-Once Code Clone Detection + MonitorTool

version: "3.8"
services:
  clone-detector:
    image: cljdetector
    command: clear
    ports:
      - "8080:3000"
    volumes:
      - ./Containers/cljdetector:/usr/src/app
      - qc-volume:/QualitasCorpus
    environment:
      DBHOST: dbstorage
      SOURCEDIRtest: "/usr/src/app/test/data"
      SOURCEDIReclipse: "/QualitasCorpus/QualitasCorpus-20130901r/Systems/eclipse_SDK"
      SOURCEDIR: "/QualitasCorpus"
      CHUNKSIZE: 20

  dbstorage:
    image: mongo
    restart: always
    command: --quiet --syslog
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - dbstorage:/data/db
      - dbconfig:/data/configdb

  monitor-tools:
    build:
      context: ./Containers/MonitorTool
    image: monitor-tools
    environment:
      MT_DB_URL: mongodb://dbstorage:27017/cloneDetector
      MT_TRACK_TABLES: files,chunks,candidates,clones,statusUpdates
      MT_STATUS_UPDATES_TABLE: statusupdates
      MT_SAMPLE_INTERVAL_SECONDS: "300"
      MT_SQLITE_PATH: /data/monitor.sqlite
      MT_TIMEZONE: Europe/Stockholm
    depends_on:
      - dbstorage
    # volumes:
    #   - monitor-data:/data
    ports:
      - "8081:8081"
    restart: unless-stopped


volumes:
  dbstorage:
  dbconfig:
  qc-volume:
    external: true
  # monitor-data:
